# Generated by Django 4.2 on 2024-01-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Blog',
        ),
    ]
